### PR TITLE
Fixed Group End Date Bug

### PR DESCRIPTION
**Pull request by dzwood**
### About
This PR updates the `GroupDateTime` component by adding a catch for groups that do not have a start/end date because the group has finished.

### Test Instructions
* go to a group that has ended or the end date is today and see that it loads correctly on web.

### Screenshots
image

### Closes Tickets
[CFDP-2130](https://christfellowshipchurch.atlassian.net/browse/CFDP-2130)

[CFDP-2130]: https://christfellowshipchurch.atlassian.net/browse/CFDP-2130?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by MsMaghan — DISMISSED** [review]
Works Great! - Approved

**Comment by dzwood** [comment]
### Update
If end date is today display Date/Time and allow check in.

**Review by natashasthilaire — APPROVED** [review]
Looks great!

**Review by codingwithlis — APPROVED** [review]
Looks great!

**Pull request merged**
