### PR TITLE
Made modals scrollable

### PR DESCRIPTION
**Pull request by leoalfonso14**
### About
All modal are now scrollable instead of the text overflowing and not being able to click the submit or save button at the bottom.

### Test Instructions
1.  Go on any page on testing page ( [Home Page](https://rock.christfellowship.church/page/4212?ContentItemId=14407) ),  on a device with a big screen, scroll to the footer at the bottom of the page and click on `Connect Card` you should see that now everything loads.
2. Go to the [Home Page](https://www.christfellowship.church/) on the website and see how it used to be.
4. Go to a different modal on the live website, for example, when you sign in and go to `My Groups` and click on a group, then click on `Manage Group` then click on `View` on any of the members and you will see that it also does not fit in the screen.
5. Try the same thing in the testing link and see the difference.

### Screenshots
|How it used to be|With the changes|
|--|--|
|Screenshot 2023-06-30 at 4 06 57 PM|Screenshot 2023-06-30 at 4 07 33 PM|

How it used to be|With the changes|
|--|--|
|Screenshot 2023-06-30 at 4 06 57 PM|Screenshot 2023-06-30 at 4 07 33 PM|

### Closes Tickets
[CFDP-2654](https://christfellowshipchurch.atlassian.net/browse/CFDP-2654)
[CFDP-2495](https://christfellowshipchurch.atlassian.net/browse/CFDP-2495)

[CFDP-2654]: https://christfellowshipchurch.atlassian.net/browse/CFDP-2654?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by natashasthilaire — DISMISSED** [review]
Great job!

**Review by codingwithlis — APPROVED** [review]
Works great! great job

**Comment by dzwood** [comment]
@leoalfonso14 I added some additional styling to keep the form from getting squished in a weird way. Great job on this 👊

**Review by dzwood — APPROVED** [review]

**Review by natashasthilaire — APPROVED** [review]
Awesome work!

**Pull request merged**
