### PR TITLE
Fix add remove content resources

### PR DESCRIPTION
**Pull request by jordanwade**
Fixes adding and removing content items and hides resource items that do not have titles.

TO TEST:
Try adding and removing a content item to a groups resources. Also double check to make sure adding and removing a url still works.

### CODE REVIEW

**Review by drewbarontini — APPROVED** [review]

**Comment by asleepingpanda** [comment]
I am unable to load the site while logged in. I log in and press my Profile Photo on the navigation bar and it throws an error. Every page load across the entire site crashes from that point on.

**Comment by rkdavidson** [comment]
Worked as expected for me 👍

**Review by rkdavidson — APPROVED** [review]

**Comment by asleepingpanda** [comment]
@rkdavidson this is what I'm seeing on the preview link
image

**Comment by asleepingpanda** [comment]
So far only on this PR. I'll pull it locally and see if I can replicate the issue. If I can't, we should just merge it.

**Comment by asleepingpanda** [comment]
Yeah super weird. Locally it all runs perfectly fine. No idea what's going on here so it's probs nothing to worry about. Maybe just a weird thing with the deploy link or something.

**Review by asleepingpanda — APPROVED** [review]

**Pull request merged**
