### PR TITLE
Add help everywhere

### PR DESCRIPTION
**Pull request by jordanwade**
Updated on community and community single pages
image

### CODE REVIEW

**Comment by drewbarontini** [comment]
@jordanwade I think we should try using a plain link for "Need help?" rather than a secondary button. What do you think?

**Comment by jordanwade** [comment]
@drewbarontini CustomLink?
image

**Review by rkdavidson — APPROVED** [review]
@jordanwade This looks good, only place I could see it being valuable — as if we don't have enough already 🙃  — is on the empty search results screen, too.

But I'll leave that up to you.

**Comment by jordanwade** [comment]
@rkdavidson I was going to put some thoughts toward that today too. 👍

**Pull request merged**
