### PR TITLE
Manage Group Photo & Resources

### PR DESCRIPTION
**Pull request by drewbarontini**
### 📣 About
This adds MVP functionality for Group Leaders to manage their Group. It takes a different approach than the current version on `web-app`, which will set us up nicely for bringing over managing members and attendance from the GLT.

This allows Group Leaders to:
- Change the photo.
- Add resources (URL and content).
- Remove resources.

CleanShot 2021-04-23 at 14 16 13@2x

screencapture-local-christfellowship-church-3000-groups-cfdp-testing-group-manage-2021-04-23-14_13_14

screencapture-local-christfellowship-church-3000-groups-cfdp-testing-group-manage-2021-04-23-14_17_23

### ✨ Code Highlights
- Adds a new `GroupManage` top-level component with a collection of sub-components.
- Adds new Hooks and Providers for querying/mutating the photo and resource data.
- Adds a `GroupManageProvider` to provide group data and states to all nested components.

### 👀 Testing

**Getting to the Group Manage screen.**
- Visit one of your Groups where you are a Group Leader.
- Click on the gear icon next to the Group name.
- You should go to `/groups/:id/manage`.
- You should be able to click between `Update Photo` and `Update Resources`.
- You should see the active photo.

**Updating the photo.**
- Click on "Update" above the photo.
- Select another image than the current one (marked with "Current Image").
- It should go back to the root page and update the photo.

**Adding a URL resource.**
- Go to "Update Resources".
- Click on "Add > Add URL".
- Fill out a title and URL.
- Click "Add Link".
- It should take you back to the resources list and show the new link.

**Adding a content resource.**
- Go to "Update Resources".
- Click on "Add > Add Content".
- Select a content item in the dropdown.
- Click "Add Content".
- It should take you back to the resources list and show the new item.

**Removing a resource.**
- Go to "Update Resources".
- Click the "x" next to any resource.
- Click the confirmation dialog.
- It should remove the item.

### CODE REVIEW

**Comment by asleepingpanda** [comment]
@drewbarontini rough status check on this?

**Comment by drewbarontini** [comment]
@asleepingpanda Working on adding content resources and then fixing removing resources and it'll be ready. Need to put my head down and knock it out right now.

**Comment by drewbarontini** [comment]
Everything here is wired up correctly, but removing a resource and adding a content resource (study) is just returning `null` and not actually removing/adding, respectively.

**Comment by rkdavidson** [comment]
@drewbarontini pushed quick, small commit 2321a50 to center the loader on `GroupSingle`:

**Review by rkdavidson — APPROVED** [review]
Pushed another small commit e0b78425458d7c5d9d3d003bfdef9f0242dd4954 to fix an issue where since I wasn't in the first 3 leaders being queried, I couldn't manage the group.

Increased that to 10 for now, but long term we may need to revisit this. Seems like there should be a flag returned from the API or cleaner mechanism like that.

Also opened issue #108 for fast follow next week. Adding a URL resource with the same name and URL combination causes a 500 error.

**Comment by asleepingpanda** [comment]
> Everything here is wired up correctly, but removing a resource and adding a content resource (study) is just returning `null` and not actually removing/adding, respectively.

@drewbarontini we noticed that there is currently a bug in production with the physical management of resources and urls. We have it as a ticket to hit this sprint to look into it. I agree that the API level error shouldn't stop us from reviewing/merging this, though. We can track that issue [here](https://github.com/christfellowshipchurch/apollos-api/issues/228)

**Comment by drewbarontini** [comment]
@asleepingpanda Perfect! We're going to merge this in and we can help out there then! 🚀

**Pull request merged**
