### PR TITLE
Removed glass Header to LocationSingle

### PR DESCRIPTION
**Pull request by dzwood**
## What's this for?
We wanted to remove the frosted glass title on the `LocationSingle` pages per request. This PR removes the frosted glass and moves title below the banner image.

## Demo/Screenshots
* go to `/locations` and click on any of the campus locations

image

## Jira Tickets
[CFDP-1389]

[CFDP-1389]: https://christfellowshipchurch.atlassian.net/browse/CFDP-1389

### CODE REVIEW

**Comment by asleepingpanda** [comment]
@dzwood I really don't like it... Let me sit on it for a minute and see if we can come up with a better solution. You have any thoughts/suggestions?

**Comment by dzwood** [comment]
@asleepingpanda I grabbed the styling from `PageSingle` center-aligned the text title this may be a workable alternative:

image

**Comment by asleepingpanda** [comment]
I like that a LOT. But I think we need to make the image much larger in order to appease any concerns that it's just an image of the sky. Lol.

Can you set the Image Height to like 80 or 90vh?

**Comment by dzwood** [comment]
@asleepingpanda this is `80vh` lol:

image

**Comment by asleepingpanda** [comment]
Yeah... is the photo center aligned?

**Comment by dzwood** [comment]
> Yeah... is the photo center aligned?

Yup...

**Comment by asleepingpanda** [comment]
Aight give me a few minutes to play around with it

**Comment by dzwood** [comment]
> Aight give me a few minutes to play around with it

Alright I committed the changes I have so far.

**Review by asleepingpanda — APPROVED** [review]

**Pull request merged**
