### PR TITLE
External Home 2.0

### PR DESCRIPTION
**Pull request by dzwood**
### About
This PR introduces the External Home Page 2.0 as seen from our [Figma Mockup](https://www.figma.com/file/aG6uLL1GHNB3u5ynLzw7C3/External-Marketing-Site?type=design&node-id=3451%3A3502&mode=design&t=Vvo95MhLCiFl44zz-1).

### Test Instructions
1. Go to the External Home Page on [our live website](https://www.christfellowship.church/)
2. Go to the External Home Page on [the testing link](https://web-app-v2-git-home-value-heade-ce1a44-christ-fellowship-church.vercel.app//) and see the differences between the buttons.
3. Look at Mobile View as well.
4. Compare the Testing Link Buttons to Figma Design, they should look the same.

### Screenshots
|How it used to be|With the changes|
|--|--|
|Screenshot 2023-08-01 at 11 11 46 AM|Screenshot 2023-08-01 at 11 12 54 AM|

### Closes Tickets
[CFDP-2634](https://christfellowshipchurch.atlassian.net/browse/CFDP-2634)

[CFDP-2634]: https://christfellowshipchurch.atlassian.net/browse/CFDP-2634?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by dzwood** [comment]
@leoalfonso14 The Hero Section is looking MUCH better! I noticed a couple more things if you could take a look. 

|The title section sits too close to the top on both mobile and desktop, if we could move it down to match Figma more that would be great. | On mobile, the buttons look pretty big, if we could adjust the fonts and spacing to match Figma more that would be great also |
|---|---|
|image|image|

**Review by codingwithlis — COMMENTED** [review]
**The button has to be fixed when signed on, and what is the logic for Sign Out?**

Screen Shot 2023-08-23 at 3 31 58 PM

**Review by codingwithlis — COMMENTED** [review]
**Adjust top padding above Life can be complicated, for mobile**
Screen Shot 2023-08-23 at 3 43 25 PM

**Remove orange dots from iPad view**
Screen Shot 2023-08-23 at 3 43 01 PM

**Comment by dzwood** [comment]
@leoalfonso14 We can use this for Logged In/Out states for the navbar:
image
You can see the examples above in Figma.

**Pull request merged**
