### PR TITLE
Updated styling for Edit Group Buttons

### PR DESCRIPTION
**Pull request by dzwood**
## What does this do?
Changes text and button styling for `GroupManage`. We wanted to have more obvious styling/language so the user knows what area they're editing for their Group.

## Demo/Screenshots
image
## Jira Tickets
[CFDP-1363]

[CFDP-1363]: https://christfellowshipchurch.atlassian.net/browse/CFDP-1363

### CODE REVIEW

**Comment by drewbarontini** [comment]
One comment I'd make around this design is that these are navigation items, not actions. I saw this designed similar to how you'd see the settings sidebar on a GitHub repo.

CleanShot 2021-05-06 at 11 33 06@2x

**Comment by asleepingpanda** [comment]
> One comment I'd make around this design is that these are navigation items, not actions. I saw this designed similar to how you'd see the settings sidebar on a GitHub repo.
> 

@dzwood that's a good point. The core problem was that it wasn't obvious enough that you can select each of the options. I think we take the background color "selected" styling on the pills and apply it to the entire row so that it mimics that GitHub screenshot example that you posted.

Good call @drewbarontini !

**Review by asleepingpanda — CHANGES_REQUESTED** [review]
See comment above

**Review by codingwithlis — DISMISSED** [review]
Looks great!

**Comment by dzwood** [comment]
I updated the styling for the buttons, new screenshot in the PR description. Good call @drewbarontini !

**Review by asleepingpanda — CHANGES_REQUESTED** [review]
Looks awesome! One last quick thing. Would you be able to add a cyan border to the lefthand side of the selected item? 2 or 3 pixels.

**Review by asleepingpanda — APPROVED** [review]

**Pull request merged**
