### PR TITLE
Group Filters bugs and refinements

### PR DESCRIPTION
**Pull request by rkdavidson**
## About
Fixes a handful of odds-and-ends related to Group Filters state management and navigation flows:

- Clicking a Lineup / `subPreference` card silently selects it and opens Group Filters modal
- Always show all Lineup / `subPreference` options on search page
- 🐞  Preference ("/crew", etc) isn't always hydrated from URL
- 🐞  Redirect from invalid group preference page URLs

## Testing
Test all variations of the end-to-end flows.
Verify that landing on a given URL always hydrates state values as expected — you can verify by going through Finder flow and seeing what filters were selected.

Open modal, change values, close it, open it again, select different ones and search. Verify the last selections are always correct. 

**Note** there is still some bugs re: the Clear and Apply buttons, and when/how the filter updates happen within the `GroupFilterAll` modal accessible from the **Search** page.

## Screenshots
|Caption|Gif|
|---|---|
|Happy path flow|Happy Path|
|Redirect from invalid preference URLs|redirect-invalid-prefs|
|Hydrate preference from URL|selecting-preference-from-url|
|Select and hydrate sub-preference from URL|selecting-subpreference|
|Show all preference and sub-preference options on Search page|selecting-subpreference|

### CODE REVIEW

**Comment by drewbarontini** [comment]
@rkdavidson Looking good! I did notice, in the happy-path flow, that I can click on a lineup and fire up the modal, bypassing authentication (I was signed out).

**Comment by rkdavidson** [comment]
> @rkdavidson Looking good! I did notice, in the happy-path flow, that I can click on a lineup and fire up the modal, bypassing authentication (I was signed out).

Oh, good catch! Can fix that quickly. I'll validate the community single page flow for that unauth state too, in case you didn't.

**Comment by rkdavidson** [comment]
@drewbarontini, I added the auth enforcement step in fd211b8.

**Review by drewbarontini — APPROVED** [review]
Very nice! 👍

**Pull request merged**
