### PR TITLE
Updated Share Button

### PR DESCRIPTION
**Pull request by natashasthilaire**
### About
* Updated Share Button component to hide the text "Share" on mobile to provide more space and have it display on larger screens. 
* Also moved Share button on mobile to remove unnecessary space.

### Test Instructions
1. Go to https://web-app-v2-git-buttontext-christ-fellowship-church.vercel.app/studies/christfellowship-howtostudythebible
2. Go to inspect and inspect mobile. Button should only display logo. 
3. Compare with live version which can be found at https://www.christfellowship.church/studies/christfellowship-howtostudytheBible

### Screenshots
|Desktop|Mobile|
|---|---|
|Screenshot 2023-06-05 at 11 07 49 AM|image|

### Closes Tickets
[CFDP-2564](https://christfellowshipchurch.atlassian.net/browse/CFDP-2564)
[CFDP-2578](https://christfellowshipchurch.atlassian.net/browse/CFDP-2578)

[CFDP-2564]: https://christfellowshipchurch.atlassian.net/browse/CFDP-2564?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CFDP-2578]: https://christfellowshipchurch.atlassian.net/browse/CFDP-2578?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by leoalfonso14 — APPROVED** [review]
Looks good!

**Review by MsMaghan — APPROVED** [review]
Approved PR - Button Works great on Testing Link

**Review by codingwithlis — APPROVED** [review]
Great job!

**Review by codingwithlis — APPROVED** [review]
Looks great

**Pull request merged**
