### PR TITLE
Add about page

### PR DESCRIPTION
**Pull request by jordanwade**
image

### CODE REVIEW

**Review by drewbarontini — COMMENTED** [review]
It looks like `public/about-christ-fellowship-church.jpeg` is clocking in at 18.4 MB, so we might want to figure out how to get that down substantially 😬

**Review by rkdavidson — COMMENTED** [review]
Nice job with the maintainable-static approach 💪 .

Found a rough mobile spot with the **Our History** content, and the line heights in the tab links, but otherwise feels shippabe.



I'll call out the `md` size stacking feels a bit tight here too, but it looks better slightly smaller and bigger — so not sure how many devices realistically fall in this ~500px width range.
Not a big deal IMO.

**Comment by dzwood** [comment]
@jordanwade Really like how this came out🔥 I agree with @rkdavidson , if we can just clean up the mobile view I think we should be good to go. I noticed some issues with the Hero block at the top in mobile and the text overflowing. If we can just have it reflect our current site that would be great. Thank @jordanwade !!
image

**Comment by drewbarontini** [comment]
@jordanwade I fired up Photoshop to save out that image and get it down to ~100kb and then just ran all the images through an optimizer.

CleanShot 2021-04-12 at 12 38 57@2x

My only other comment would be making the active "tab" link have a different style so it's clear it's active.

But I'll approve once the build passes 👍

**Review by drewbarontini — APPROVED** [review]
Approving with a few notes we should track as separate tasks:
- Move `public/` images into a `public/about` sub-folder.
- Add an active style for the "tab" links.

**Pull request merged**
